set(_CATKIN_CURRENT_PACKAGE "dynamixel_driver")
set(dynamixel_driver_VERSION "0.4.1")
set(dynamixel_driver_MAINTAINER "Antons Rebguns <arebgun@gmail.com>")
set(dynamixel_driver_PACKAGE_FORMAT "1")
set(dynamixel_driver_BUILD_DEPENDS )
set(dynamixel_driver_BUILD_EXPORT_DEPENDS "rospy" "diagnostic_msgs" "python-serial")
set(dynamixel_driver_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_driver_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_driver_EXEC_DEPENDS "rospy" "diagnostic_msgs" "python-serial")
set(dynamixel_driver_RUN_DEPENDS "rospy" "diagnostic_msgs" "python-serial")
set(dynamixel_driver_TEST_DEPENDS )
set(dynamixel_driver_DOC_DEPENDS )
set(dynamixel_driver_URL_WEBSITE "http://ros.org/wiki/dynamixel_driver")
set(dynamixel_driver_URL_BUGTRACKER "https://github.com/arebgun/dynamixel_motor")
set(dynamixel_driver_URL_REPOSITORY "")
set(dynamixel_driver_DEPRECATED "")