set(_CATKIN_CURRENT_PACKAGE "cups")
set(cups_VERSION "0.0.0")
set(cups_MAINTAINER "trevor <trevor@todo.todo>")
set(cups_PACKAGE_FORMAT "2")
set(cups_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(cups_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(cups_BUILDTOOL_DEPENDS "catkin")
set(cups_BUILDTOOL_EXPORT_DEPENDS )
set(cups_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(cups_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(cups_TEST_DEPENDS )
set(cups_DOC_DEPENDS )
set(cups_URL_WEBSITE "")
set(cups_URL_BUGTRACKER "")
set(cups_URL_REPOSITORY "")
set(cups_DEPRECATED "")