set(_CATKIN_CURRENT_PACKAGE "ebolabot")
set(ebolabot_VERSION "2.0.0")
set(ebolabot_MAINTAINER "Ozan Akyildiz <oakyildiz@wpi.edu>")
set(ebolabot_PACKAGE_FORMAT "1")
set(ebolabot_BUILD_DEPENDS )
set(ebolabot_BUILD_EXPORT_DEPENDS "ebolabot_description" "ebolabot_bringup" "ebolabot_system_configuration" "ebolabot_hstar_amp")
set(ebolabot_BUILDTOOL_DEPENDS "catkin")
set(ebolabot_BUILDTOOL_EXPORT_DEPENDS )
set(ebolabot_EXEC_DEPENDS "ebolabot_description" "ebolabot_bringup" "ebolabot_system_configuration" "ebolabot_hstar_amp")
set(ebolabot_RUN_DEPENDS "ebolabot_description" "ebolabot_bringup" "ebolabot_system_configuration" "ebolabot_hstar_amp")
set(ebolabot_TEST_DEPENDS )
set(ebolabot_DOC_DEPENDS )
set(ebolabot_URL_WEBSITE "http://sdk.rethinkrobotics.com")
set(ebolabot_URL_BUGTRACKER "http://solar-10.wpi.edu/hiro/ros_ws/issues")
set(ebolabot_URL_REPOSITORY "http://solar-10.wpi.edu/hiro/ros_ws")
set(ebolabot_DEPRECATED "")