set(_CATKIN_CURRENT_PACKAGE "dynamixel_motor")
set(dynamixel_motor_VERSION "0.4.1")
set(dynamixel_motor_MAINTAINER "Antons Rebguns <arebgun@gmail.com>")
set(dynamixel_motor_PACKAGE_FORMAT "1")
set(dynamixel_motor_BUILD_DEPENDS )
set(dynamixel_motor_BUILD_EXPORT_DEPENDS "dynamixel_tutorials" "dynamixel_msgs" "dynamixel_controllers" "dynamixel_driver")
set(dynamixel_motor_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_motor_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_motor_EXEC_DEPENDS "dynamixel_tutorials" "dynamixel_msgs" "dynamixel_controllers" "dynamixel_driver")
set(dynamixel_motor_RUN_DEPENDS "dynamixel_tutorials" "dynamixel_msgs" "dynamixel_controllers" "dynamixel_driver")
set(dynamixel_motor_TEST_DEPENDS )
set(dynamixel_motor_DOC_DEPENDS )
set(dynamixel_motor_URL_WEBSITE "http://ros.org/wiki/dynamixel_driver")
set(dynamixel_motor_URL_BUGTRACKER "https://github.com/arebgun/dynamixel_motor")
set(dynamixel_motor_URL_REPOSITORY "")
set(dynamixel_motor_DEPRECATED "")