set(_CATKIN_CURRENT_PACKAGE "dynamixel_tutorials")
set(dynamixel_tutorials_VERSION "0.4.1")
set(dynamixel_tutorials_MAINTAINER "Antons Rebguns <arebgun@gmail.com>")
set(dynamixel_tutorials_PACKAGE_FORMAT "1")
set(dynamixel_tutorials_BUILD_DEPENDS )
set(dynamixel_tutorials_BUILD_EXPORT_DEPENDS "dynamixel_controllers")
set(dynamixel_tutorials_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_tutorials_EXEC_DEPENDS "dynamixel_controllers")
set(dynamixel_tutorials_RUN_DEPENDS "dynamixel_controllers")
set(dynamixel_tutorials_TEST_DEPENDS )
set(dynamixel_tutorials_DOC_DEPENDS )
set(dynamixel_tutorials_URL_WEBSITE "http://ros.org/wiki/dynamixel_driver")
set(dynamixel_tutorials_URL_BUGTRACKER "https://github.com/arebgun/dynamixel_motor")
set(dynamixel_tutorials_URL_REPOSITORY "")
set(dynamixel_tutorials_DEPRECATED "")