set(_CATKIN_CURRENT_PACKAGE "baxter_pykdl")
set(baxter_pykdl_VERSION "0.1.0")
set(baxter_pykdl_MAINTAINER "Kyle Maroney <kmaroney@rethinkrobotics.com>")
set(baxter_pykdl_PACKAGE_FORMAT "1")
set(baxter_pykdl_BUILD_DEPENDS "rospy" "baxter_core_msgs" "baxter_interface" "geometry_msgs" "sensor_msgs" "liburdfdom-dev" "python_orocos_kdl" "tf")
set(baxter_pykdl_BUILD_EXPORT_DEPENDS "rospy" "baxter_core_msgs" "baxter_interface" "geometry_msgs" "sensor_msgs" "urdfdom" "python_orocos_kdl" "tf")
set(baxter_pykdl_BUILDTOOL_DEPENDS "catkin")
set(baxter_pykdl_BUILDTOOL_EXPORT_DEPENDS )
set(baxter_pykdl_EXEC_DEPENDS "rospy" "baxter_core_msgs" "baxter_interface" "geometry_msgs" "sensor_msgs" "urdfdom" "python_orocos_kdl" "tf")
set(baxter_pykdl_RUN_DEPENDS "rospy" "baxter_core_msgs" "baxter_interface" "geometry_msgs" "sensor_msgs" "urdfdom" "python_orocos_kdl" "tf")
set(baxter_pykdl_TEST_DEPENDS )
set(baxter_pykdl_DOC_DEPENDS )
set(baxter_pykdl_URL_WEBSITE "http://sdk.rethinkrobotics.com/wiki")
set(baxter_pykdl_URL_BUGTRACKER "https://github.com/rethink-kmaroney/baxter_pykdl/issues")
set(baxter_pykdl_URL_REPOSITORY "https://github.com/rethink-kmaroney/baxter_pykdl")
set(baxter_pykdl_DEPRECATED "")