set(_CATKIN_CURRENT_PACKAGE "dynamixel_controllers")
set(dynamixel_controllers_VERSION "0.4.1")
set(dynamixel_controllers_MAINTAINER "Antons Rebguns <arebgun@gmail.com>")
set(dynamixel_controllers_PACKAGE_FORMAT "1")
set(dynamixel_controllers_BUILD_DEPENDS "message_generation")
set(dynamixel_controllers_BUILD_EXPORT_DEPENDS "rospy" "actionlib" "std_msgs" "trajectory_msgs" "diagnostic_msgs" "dynamixel_msgs" "control_msgs" "dynamixel_driver")
set(dynamixel_controllers_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_controllers_EXEC_DEPENDS "rospy" "actionlib" "std_msgs" "trajectory_msgs" "diagnostic_msgs" "dynamixel_msgs" "control_msgs" "dynamixel_driver")
set(dynamixel_controllers_RUN_DEPENDS "rospy" "actionlib" "std_msgs" "trajectory_msgs" "diagnostic_msgs" "dynamixel_msgs" "control_msgs" "dynamixel_driver")
set(dynamixel_controllers_TEST_DEPENDS )
set(dynamixel_controllers_DOC_DEPENDS )
set(dynamixel_controllers_URL_WEBSITE "http://ros.org/wiki/dynamixel_controllers")
set(dynamixel_controllers_URL_BUGTRACKER "https://github.com/arebgun/dynamixel_motor")
set(dynamixel_controllers_URL_REPOSITORY "")
set(dynamixel_controllers_DEPRECATED "")